version: '3.9'

services:
  dev:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_TMDB_ACCESS_TOKEN=${VITE_TMDB_ACCESS_TOKEN}

  prod:
    build:
      context: .
      target: production
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - VITE_TMDB_ACCESS_TOKEN=${VITE_TMDB_ACCESS_TOKEN} 